Run call Downloads.bat default1
  call Downloads.bat default1
  shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    PROFILE: default1
    LITEMANAGER_ID: 
    LITEMANAGER_PASS: 
'Downloads.bat' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 1.
